### ISSUE TITLE
Speed tests: add test for largest data

### ISSUE THREAD

**Issue by skynowa** [c42f/tinyformat#22]
```C++
    #define str \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg" \
        "asdcf'awsrk.fw3[045im2,[4oc'wxe;/fzd1[-,c4rxj.wk;szlcgjx34-rx134rxqwetaertg"
...
    } else if (which == "tinyformat") {
        for (long i = 0; i < loops; ++ i) {
            tfm::printf("%0.10f" str "%04d" str "%+g" str "%s" str "%p" str "%c" str "%%\n",
                1.234, 42, 3.13, "string", (void *)1000, (int)'X');
        }
    }
...
```

**Comment by c42f** [comment]
Sorry for the delay, I forgot about this.

Your second example is testing something quite different from the first, so I'm still not quite sure what the intention is here.

* Your first suggestion tests the speed at which tinyformat processes a really long format string.  This may be of some interest in particular use cases.
* Your second suggestion tests the speed at which a string argument can be handled when printing with `"%s"`.  This is really testing the underlying implementation of `operator<<(std::ostream&, const char*)`, but I guess it might be of interest to someone.

Neither of these seem like particularly typical use cases, so I probably wouldn't put them in the main speed test - it is meant to be a simple "smoke test" to check that nothing has gone horribly wrong.  However, if you'd care about performance, I'd encourage you to submit a pull request expanding the speed test into a full test suite with various different cases of interest.  In that case I think it would make sense to compare against both libc printf and iostreams (`boost::format` is so far behind that we may as well ignore it)
