### ISSUE TITLE
AppVeyor continuous integration

### ISSUE THREAD

**Issue by kainjow** [c42f/tinyformat#36]
You've got Travis setup but it'd be good to integrate AppVeyor which has VS 2013 through 2017.

**Comment by kainjow** [comment]
Also Travis build could be expanded to use macOS/Clang.

**Comment by c42f** [comment]
Well, this was more effort than you'd probably expect!  Travis is now using a largish build matrix with g++ and clang++ on linux, clang on osx, and appveyor now enabled for visual studio 12 and 14.  See #37.

**Comment by kainjow** [comment]
Cool! One last thing I would suggest is adding the badges to the read me.
