### ISSUE TITLE
Empty FormatArg() constructor doesn't initialize members

### ISSUE THREAD

**Issue by krlmlr** [c42f/tinyformat#42]
https://github.com/c42f/tinyformat/blob/46a6d778e7abafa057efc546197603d32719bfc5/tinyformat.h#L490

This confuses Coverity, and also looks unsafe:

![screenshot from 2017-10-02 09-25-09](https://user-images.githubusercontent.com/1741643/31097786-d5d7c5e0-a7c0-11e7-918b-00fdc8e51768.png)

Reference: https://github.com/RcppCore/Rcpp/issues/760

**Comment by nigels-com** [comment]
Agreed.  NULLing out the pointers would be correct.

**Comment by c42f** [comment]
Thanks Nigel for #43 - this should eliminate the warning (please feel free to reopen if you still have issues).

As a side note, I'm quite sure this was in fact a false alarm as other internal implementation details ensure these pointers are always initialized.  However, it's always good to keep the warnings to a minimum.

**Comment by krlmlr** [comment]
Thanks. Agreed that the implementation may have been correct before, but it still feels safer to initialize.

**Comment by krlmlr** [comment]
Thanks. Agreed that the implementation may have been correct before, but it still feels safer to initialize.
