### ISSUE TITLE
Support for POSIX extension of positional arguments

### ISSUE THREAD

**Issue by jrohel** [c42f/tinyformat#46]
I was looking for simple formating string support for C++ with the ability to rearrange formating arguments.

The ability to rearrange formatting arguments is an important feature for localization because the word order may vary in different languages.

I found tinyformat but it does not support rearrange formatting arguments. Without this support the tinyformat is not usable in projects where localization is required.

So, I had choices: Search for another library or write new one or improve tinyformat.
I decided to improve tinyformat and I made PR #45 wich adds support for POSIX extension of positional arguments.

I think tinyformat will be usable for more users and projects with my PR.
Thanks for tinyformat. Have a nice day.

**Comment by willwray** [comment]
What's the status?
Is the PR branch good to go?

**Comment by c42f** [comment]
Fixed in #45
