### ISSUE TITLE
const std::atomic  actual parameter with requested alignment of 8 won't be aligned

### ISSUE THREAD

**Issue by shafeng** [c42f/tinyformat#47]
when i use tinyformat in vs2015,this line was error:

sizeof(tryConvert(makeT1())) == sizeof(succeed);

error C2178 const std::atomic  actual parameter with requested alignment of 8 won't be aligned

how to fix it?

**Comment by shafeng** [comment]
line number is :201

**Comment by c42f** [comment]
The line you're having trouble with inside `is_convertible` was a hack required for compilers which are quite old now.  C++11 supplies the `<type_traits>` header, including `std::is_convertible`, so you could try removing `is_convertible` and using `std::is_convertible`?

**Comment by shafeng** [comment]
@c42f 
Thank you ,  Maybe my C++ compiler without C++11 support
