### ISSUE TITLE
Use typename instead of class on TINYFORMAT_ARGTYPES?

### ISSUE THREAD

**Issue by evandrocoan** [c42f/tinyformat#63]
Should `typename` to be more generic than `class`?

https://github.com/c42f/tinyformat/blob/705e3f4e1de922069bf715746d35bd2364b1f98f/tinyformat.h#L418

**Comment by c42f** [comment]
No, they're equivalent in this context. `typename` is just longer.

**Comment by c42f** [comment]
I'm not sure there's anything really useful to change here, so I'll close this.

I agree that `typename` is more accurate terminology. But given that it's twice as long I tend to default to `class` instead for template type parameters.
