### ISSUE TITLE
Multiple symbol definitions after commit 9368985

### ISSUE THREAD

**Issue by frithrah** [c42f/tinyformat#79]
Thanks for this library.

I just updated and got linker errors for multiply defined symbols on tinyformat::detail::spaceFillIfNotFinite.

Compiling with the latest MSVC.

**Comment by c42f** [comment]
Oops! Thanks for the report.  Should be fixed in #80

**Comment by frithrah** [comment]
Thank you. It was good timing that I spotted it so quickly.
